# Generated by Django 6.0 on 2026-01-02 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DataImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255)),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='SUCCESS', max_length=20)),
                ('rows_inserted', models.IntegerField(default=0)),
                ('rows_updated', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('initial_value', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='InitialHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=30)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('portfolio', 'asset'), name='uq_holding_portfolio_asset')],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.asset')),
            ],
            options={
                'indexes': [models.Index(fields=['asset', 'date'], name='portfolios__asset_i_2b7aca_idx'), models.Index(fields=['date'], name='portfolios__date_324b1a_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset', 'date'), name='uq_price_asset_date')],
            },
        ),
        migrations.CreateModel(
            name='TradeLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('side', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=4)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=20)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
            ],
            options={
                'indexes': [models.Index(fields=['portfolio', 'date'], name='portfolios__portfol_ce0977_idx'), models.Index(fields=['date'], name='portfolios__date_99cab8_idx')],
            },
        ),
    ]
